---

fail_fast: true
minimum_pre_commit_version: "1.18"

repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      -
        id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace

  -
    repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: require-ascii
      -
        id: rubocop
        name: Check Homebrew Cask style with rubocop
        args: [
          "--except='Naming/FileName'",
          "--config=../dotfiles-org/.rubocop-casks.yaml",
          "--fail-fast",
          "--extra-details"
        ]
      -
        id: shellcheck
        args: [
          "--color=auto",
          "--external-sources"
        ]
#       -
#         id: shfmt
#         args: [
#           '-l',
#           '-w',
#           '-d',
#           '-s',
#           '-i 2',
#           '-ci',
#           '-sr'
#         ]

  -
    repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.1
    hooks:
      - id: checkmake
        args: [
          "--config=../dotfiles-org/.checkmake.ini"
        ]

  -
    repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      -
        id: markdownlint
        args: [
          "--config=../dotfiles-org/.mdlrc"
        ]

  -
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.27.0
    hooks:
      - id: terraform_fmt

  -
    repo: https://github.com/operatehappy/pre-commit-hooks
    rev: 1.0.0
    hooks:
      - id: standard
