# based on https://github.com/Homebrew/brew/blob/d5a785374e7c4ef4605fea31537a497e9db6bf5f/Library/.rubocop.yml
# and https://github.com/Homebrew/brew/blob/d5a785374e7c4ef4605fea31537a497e9db6bf5f/Library/.rubocop_shared.yml

inherit_from: .rubocop.yaml

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  Include:
    - 'Casks/**.rb'
  Exclude:
    - 'helpers/templates/*.rb'
