#!/bin/sh

# script/update: Update application to run for its current checkout.

set -o errexit; set -o nounset

cd "$(dirname "$0")/.."

if [ -f ".pre-commit-config.yaml" ]; then
  echo "==> Removing current pre-commit installation..."
  pre-commit uninstall

  echo "==> Installing pre-commit dependencies..."
  pre-commit install
fi
